##  Reusable action for releases:
##  Create an release PR

name: release-PR

description: 'Run maven release in a PR'

inputs:
  baseBranch:
    description: 'The branch to release from.'
    required: true
    default: 'develop'
  releasePrefix:
    description: 'The branch to release into.'
    required: true
    default: 'develop'
  releaseVersion:
    description: 'Release version: (like x.y.z).'
    required: true
  developmentVersion:
    description: 'Development version: (like x.y.z.0-SNAPSHOT).'
    required: true
    default: ''
  msteams__github_webook:
    description: 'Teams web-hook secret'
    required: true

runs:
  using: composite

  steps:
    - name: Show Release Values
      id: show-release-values
      run: |
        echo " ** RUNNING RELEASE WITH:
        baseBranch: ${{ env.baseBranch }}
        releasePrefix: ${{ env.releasePrefix }}
        releaseVersion: ${{ env.releaseVersion }}
        developmentVersion: ${{ env.developmentVersion }}
        "
        git branch -l
      shell: bash


    - name: Start ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}
      # See https://github.com/peter-evans/create-pull-request
      uses: peter-evans/create-pull-request@v5
      id: create-release-pr
      with:
        # Default repo-branch to branch off this PR
        base: ${{ inputs.baseBranch }}
        # Branch name for of the PR to create
        branch: "${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}"
        title: "${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}"
        commit-message: Start release ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}
        reviewers: radiomix
        body: |
          ## Release `${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}`
          - Release version: `${{ inputs.releaseVersion }}`
          - Development version: `${{ inputs.developmentVersion }}`
          - Tag: [${{ env.artifact-id }}-${{ inputs.releaseVersion }}](https://github.com/radiomix/gh-composite-action/releases/tag/${{ env.artifact-id }}-${{ inputs.releaseVersion }})

          -------------

          - [ ] Change log has been added
          - [ ] New feature are described
          - [ ] Breaking change are described
          - [ ] Documentation has been update

          -------------

          - [ ] previous/related PR:
          - [ ] Jira Card:
          - [ ] Teams Channel:
          - [ ] Slack Channel:
        labels: ${{ inputs.releasePrefix }}

    # Prepare git and ensure peter-evans/create-pull-request creates a new PR
    - name: Prepare ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}
      id: setup-git
      run: |
        git config --global user.email "GithubAction@support.eyefreight.com"
        git config --global user.name " Github Actions"
        echo "****** git config -l --global *******"
        git config -l --global
        git branch -l
        echo "" >> releases.txt
        echo "New ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }} with:" >> releases.txt
        git add releases.txt
      shell: bash

    - name: Release:Prepare ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}
      id: prepare-release
      run: |
        git branch -l
        echo " Phase PREPARE" >> release.txt
        git add release.txt
        git commit -m "PREPARE ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}"
      shell: bash

    - name: Release:Perform ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}
      id: perform-release
      run: |
        git branch -l
        echo " Phase PEFORM" >> release.txt
        git add release.txt
        git commit -m "PERFORM ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}"
      shell: bash

    - name: Finish ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}
      id: write-release-values
      run: |
        git branch -l
        echo " - Base Branch              - ${{ inputs.baseBranch }}" >> releases.txt
        echo " - Target Branch            - ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}"  >> releases.txt
        echo " - Release Version          - ${{ inputs.releaseVersion }}"  >> releases.txt
        echo " - Development Version      - ${{ inputs.developmentVersion }}"  >> releases.txt
        echo " - Pull Request URL         - ${{ steps.create-release-pr.outputs.pull-request-url }}" >> releases.txt
        echo " - Pull Request operation   - ${{ steps.create-release-pr.outputs.pull-request-operation }}" >> releases.txt
        echo " - Pull Request Commit SHA  - ${{ steps.create-release-pr.outputs.pull-request-head-sha }}" >> releases.txt
        echo " - Tag:                     - https://github.com/radiomix/gh-composite-action/releases/tag/${{ env.artifact-id }}-${{ inputs.releaseVersion }}" >> releases.txt
        echo " - Time                     - $(date -u )" >> releases.txt
        echo " -------------------------- " >> releases.txt
        git add releases.txt
        git commit -m "Finish ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}"
        git push -u origin ${{ inputs.releasePrefix }}/${{ inputs.releaseVersion }}
      shell: bash
