#
#
# Source:
#  - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#  - https://dev.to/n3wt0n/github-composite-actions-nest-actions-within-actions-3e5l
# Purpose: call a composite action created by ourself
#
name: Composite Example

on: [workflow_dispatch]

jobs:
  create_files_job:
    runs-on: ubuntu-latest
    name: Call action.yaml
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        # From https://github.com/actions/cache/blob/main/examples.md#java---maven
        uses: actions/cache@v2

      - name: Call composite action
        id: myCompositeAction
        # the `uses' attribute must be a path, a Docker image, or owner/repo@ref
        uses:  radiomix/gh-composite-action/.github/composite/action.yaml@main
        with:
          fileName: 'caller-date-file.txt'

      - name: Log output
        run: |
          echo "Created File Content: ${{ steps.date-generator.outputs.fileContent }}"
          ls -la
        shell: bash
