# Purpose call another action in the same repo
#
# Source:
#  - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#  - https://dev.to/n3wt0n/github-composite-actions-nest-actions-within-actions-3e5l
# Purpose: call a composite action created by ourself
#
name: use composite action
on: push

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Call composite action
      id: call-composite-action
      # https://github.community/t/path-to-action-in-the-same-repository-as-workflow/16952/2
      uses: radiomix/gh-composite-action/.github/actions@main
      with:
        fileName: 'caller-date-file.txt'

    - name: Log composite action
      run: |
        echo " Calling radiomix/gh-composite-action/.github/actions@main"
        echo "Created File Content: ${{ steps.date-generator.outputs.fileContent }}"
        ls -la
        cat ${{ call-composite-action.fileName}}

      shell: bash

    # - name: Call local action
    #   # https://github.community/t/path-to-action-in-the-same-repository-as-workflow/16952/2
    #   # ERROR: the `uses' attribute must be a path, a Docker image, or owner/repo@ref
    #   uses: .github/actions/
    #   with:
    #     fileName: 'caller-date-file.txt'

    # - name: Log local action
    #   run: |
    #     echo " Calling .github/actions/"
    #     echo "Created File Content: ${{ steps.date-generator.outputs.fileContent }}"
    #     ls -la
    #   shell: bash
