# This workflow prunes old workflow runs for an entire repository.
# Source: https://github.community/t/delete-old-workflow-results/16152/41
# Source: https://github.community/t/delete-old-workflow-results/16152/42
#

name: Workflow Run Pruner

on:
  workflow_dispatch:

jobs:
 prune_old_runs:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v2
      # Install Node 12
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm install @octokit/action
      # Node.js script can be anywhere. A good convention is to put local GitHub Actions
      # into the `.github/actions` folder
      - run: node .github/actions/prune_cancelled_skipped_runs.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # runs-on: ubuntu-latest
    # timeout-minutes: 10

    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Setup nodes and install octokit/action
    #   # Install Node 12
    #   uses: actions/setup-node@v1
    #     with:
    #       version: 12
    #   - run: npm install @octokit/action

    # - name: Prune cancelled/skipped runs
    #   run: node .github/actions/prune_cancelled_skipped_runs.js
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Prune runs older than 30 days
    #   run: node .github/actions/prune_old_runs.js
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
