# This workflow prunes old workflow runs for an entire repository.
# Source: https://github.community/t/delete-old-workflow-results/16152/41
# Source: https://github.community/t/delete-old-workflow-results/16152/42
#

name: Workflow Run Pruner

on:
  workflow_dispatch:

jobs:
 prune_old_runs:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Setup nodes
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Prune cancelled/skipped runs
      run: node .github/actions/prune_cancelled_skipped_runs.js

    - name: Prune runs older than 30 days
      run: node .github/actions/prune_old_runs.js
